# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImgageSliderDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImgageSliderDemo

  target 'ImgageSliderDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImgageSliderDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'LIHImageSlider'

end
